name: Criar Release

on:
  repository_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "package.json"
      - "package-lock.json"

env:
  PLUGIN_NAME: "shop-champion-select"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zipando o plugin
        run: zip -r ${{ env.PLUGIN_NAME }}.zip index.js README.md README.br.md

      - name: Criando a release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: ${{ env.PLUGIN_NAME }} v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Subindo nova versão
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}.zip
          asset_content_type: application/zip